name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows .exe
        run: pyinstaller -F get_report/get_report.py

      - name: Upload .exe
        uses: actions/upload-artifact@v4
        with:
          name: get_report_windows_exe
          path: dist/get_report.exe
