name: Build and Upload Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use this for a Windows .exe

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller -F get_report/get_report.py

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: get_report_exe
          path: dist/get_report.exe
